; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

lib_ldf_mode = deep+

monitor_dtr = 1
monitor_rts = 0

; Serial monitor & upload
monitor_speed = 115200
upload_speed = 921600

; 8MB Flash configuration
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; Memory & PSRAM flags
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1      ; Routes Serial monitor over native USB-C
    -D BOARD_HAS_PSRAM                ; Enables the 8MB external RAM

; Core dependencies
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.0
